import { desc, eq, like } from 'drizzle-orm'
import { getDatabase } from '../db/index'
import {
  chartOfAccounts,
  journalEntries,
  journalEntryLines,
  type Sale,
  type SaleItem,
  type Purchase,
  type PurchaseItem,
  type NewJournalEntry,
  type NewJournalEntryLine,
  reversalRequests,
} from '../db/schema'
import { createAuditLog } from './audit'

// Account Codes - these correspond to the chart of accounts
export const ACCOUNT_CODES = {
  CASH_IN_HAND: '1010',
  CASH_IN_BANK: '1020',
  ACCOUNTS_RECEIVABLE: '1100',
  INVENTORY: '1200',
  ACCOUNTS_PAYABLE: '2000',
  SALES_TAX_PAYABLE: '2100',
  COD_CHARGES_PAYABLE: '2150', // COD charges collected - liability until paid to courier
  OWNERS_CAPITAL: '3000',
  RETAINED_EARNINGS: '3100',
  SALES_REVENUE: '4000',
  INVENTORY_ADJUSTMENT: '4900', // Income from inventory surplus
  COGS: '5000',
  SALARIES_WAGES: '5100',
  RENT_EXPENSE: '5200',
  UTILITIES_EXPENSE: '5300',
  INVENTORY_SHRINKAGE: '5400', // Expense for inventory loss/damage/theft
  OTHER_EXPENSE: '5900',
} as const

interface JournalLine {
  accountCode: string
  debitAmount: number
  creditAmount: number
  description?: string
}

interface CreateJournalEntryParams {
  description: string
  referenceType: string
  referenceId: number
  branchId: number
  userId: number
  lines: JournalLine[]
  isAutoGenerated?: boolean
  entryDate?: string
}

/**
 * Generate a unique journal entry number in format JE-YYYY-NNNN
 */
function generateJournalEntryNumber(): string {
  const year = new Date().getFullYear()
  const timestamp = Date.now().toString().slice(-6)
  const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0')
  return `JE-${year}-${timestamp}${random}`
}

/**
 * Generate a unique reversal request number in format REV-YYYY-NNNN
 */
export async function generateReversalNumber(): Promise<string> {
  const db = getDatabase()
  const year = new Date().getFullYear()
  const prefix = `REV-${year}-`

  const lastEntry = await db.query.reversalRequests.findFirst({
    where: like(reversalRequests.requestNumber, `${prefix}%`),
    orderBy: [desc(reversalRequests.id)],
  })

  let nextNum = 1
  if (lastEntry?.requestNumber) {
    const lastNum = parseInt(lastEntry.requestNumber.replace(prefix, ''), 10)
    if (!isNaN(lastNum)) nextNum = lastNum + 1
  }

  return `${prefix}${String(nextNum).padStart(4, '0')}`
}

/**
 * Default account definitions for auto-creation
 */
const DEFAULT_ACCOUNTS: Record<string, {
  accountName: string
  accountType: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense'
  normalBalance: 'debit' | 'credit'
  description: string
}> = {
  '1010': {
    accountName: 'Cash in Hand',
    accountType: 'asset',
    normalBalance: 'debit',
    description: 'Cash on hand for daily transactions',
  },
  '1020': {
    accountName: 'Cash in Bank',
    accountType: 'asset',
    normalBalance: 'debit',
    description: 'Bank account balances',
  },
  '1100': {
    accountName: 'Accounts Receivable',
    accountType: 'asset',
    normalBalance: 'debit',
    description: 'Amounts owed by customers',
  },
  '1200': {
    accountName: 'Inventory',
    accountType: 'asset',
    normalBalance: 'debit',
    description: 'Merchandise inventory',
  },
  '2000': {
    accountName: 'Accounts Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    description: 'Amounts owed to suppliers',
  },
  '2100': {
    accountName: 'Sales Tax Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    description: 'Sales tax collected to be remitted',
  },
  '2150': {
    accountName: 'COD Charges Payable',
    accountType: 'liability',
    normalBalance: 'credit',
    description: 'COD charges collected - liability until paid to courier',
  },
  '3000': {
    accountName: "Owner's Capital",
    accountType: 'equity',
    normalBalance: 'credit',
    description: "Owner's invested capital and initial funding",
  },
  '3100': {
    accountName: 'Retained Earnings',
    accountType: 'equity',
    normalBalance: 'credit',
    description: 'Accumulated net income retained in the business',
  },
  '4000': {
    accountName: 'Sales Revenue',
    accountType: 'revenue',
    normalBalance: 'credit',
    description: 'Revenue from product sales',
  },
  '4900': {
    accountName: 'Inventory Adjustment Income',
    accountType: 'revenue',
    normalBalance: 'credit',
    description: 'Income from inventory surplus adjustments',
  },
  '5000': {
    accountName: 'Cost of Goods Sold',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Cost of products sold',
  },
  '5100': {
    accountName: 'Salaries & Wages',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Employee salaries and wages',
  },
  '5200': {
    accountName: 'Rent Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Rent for premises',
  },
  '5300': {
    accountName: 'Utilities Expense',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Electricity, water, gas expenses',
  },
  '5400': {
    accountName: 'Inventory Shrinkage',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Expense for inventory loss/damage/theft',
  },
  '5900': {
    accountName: 'Other Expenses',
    accountType: 'expense',
    normalBalance: 'debit',
    description: 'Miscellaneous expenses',
  },
}

/**
 * Get account ID by account code - auto-creates missing required accounts
 */
async function getAccountId(accountCode: string): Promise<number> {
  const db = getDatabase()
  let account = await db.query.chartOfAccounts.findFirst({
    where: eq(chartOfAccounts.accountCode, accountCode),
  })

  // If account doesn't exist, try to auto-create it
  if (!account) {
    const defaultAccount = DEFAULT_ACCOUNTS[accountCode]
    if (defaultAccount) {
      console.log(`Auto-creating missing GL account: ${accountCode} - ${defaultAccount.accountName}`)
      const [newAccount] = await db
        .insert(chartOfAccounts)
        .values({
          accountCode,
          accountName: defaultAccount.accountName,
          accountType: defaultAccount.accountType,
          normalBalance: defaultAccount.normalBalance,
          description: defaultAccount.description,
          currentBalance: 0,
          isActive: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        })
        .returning()
      account = newAccount
    }
  }

  if (!account) {
    throw new Error(`Account with code ${accountCode} not found and could not be auto-created`)
  }
  return account.id
}

/**
 * Create a journal entry with lines and update account balances.
 * The entry is auto-posted for system-generated entries.
 */
export async function createJournalEntry(params: CreateJournalEntryParams): Promise<number> {
  const db = getDatabase()
  const { description, referenceType, referenceId, branchId, userId, lines, isAutoGenerated = true, entryDate } = params

  // Validate that debits equal credits
  const totalDebits = lines.reduce((sum, l) => sum + l.debitAmount, 0)
  const totalCredits = lines.reduce((sum, l) => sum + l.creditAmount, 0)

  if (Math.abs(totalDebits - totalCredits) > 0.01) {
    throw new Error(`Journal entry unbalanced: Debits (${totalDebits}) != Credits (${totalCredits})`)
  }

  const entryNumber = generateJournalEntryNumber()
  const now = new Date().toISOString()

  // Create journal entry - auto-post if auto-generated
  const [entry] = await db
    .insert(journalEntries)
    .values({
      entryNumber,
      entryDate: entryDate || now.split('T')[0],
      description,
      referenceType,
      referenceId,
      branchId,
      status: isAutoGenerated ? 'posted' : 'draft',
      isAutoGenerated,
      createdBy: userId,
      postedBy: isAutoGenerated ? userId : null,
      postedAt: isAutoGenerated ? now : null,
    })
    .returning()

  // Create journal entry lines and update account balances
  for (const line of lines) {
    if (line.debitAmount === 0 && line.creditAmount === 0) {
      continue // Skip zero-amount lines
    }

    const accountId = await getAccountId(line.accountCode)

    await db.insert(journalEntryLines).values({
      journalEntryId: entry.id,
      accountId,
      debitAmount: line.debitAmount,
      creditAmount: line.creditAmount,
      description: line.description,
    })

    // Update account balance if posted
    if (isAutoGenerated) {
      const account = await db.query.chartOfAccounts.findFirst({
        where: eq(chartOfAccounts.id, accountId),
      })

      if (account) {
        // Calculate balance change based on normal balance
        let balanceChange: number
        if (account.normalBalance === 'debit') {
          balanceChange = line.debitAmount - line.creditAmount
        } else {
          balanceChange = line.creditAmount - line.debitAmount
        }

        await db
          .update(chartOfAccounts)
          .set({
            currentBalance: account.currentBalance + balanceChange,
            updatedAt: now,
          })
          .where(eq(chartOfAccounts.id, accountId))
      }
    }
  }

  // Create audit log for journal entry
  await createAuditLog({
    userId,
    branchId,
    action: 'CREATE',
    entityType: 'journal_entry',
    entityId: entry.id,
    newValues: {
      entryNumber: entry.entryNumber,
      description,
      referenceType,
      referenceId,
      status: entry.status,
      totalDebits: lines.reduce((sum, l) => sum + l.debitAmount, 0),
      totalCredits: lines.reduce((sum, l) => sum + l.creditAmount, 0),
      lineCount: lines.length,
    },
    description: `Journal entry ${entry.entryNumber} created for ${referenceType} #${referenceId}`,
  })

  return entry.id
}

interface PaymentBreakdownForGL {
  method: 'cash' | 'card' | 'debit_card' | 'mobile' | 'cheque' | 'bank_transfer' | 'cod'
  amount: number
  referenceNumber?: string
}

/**
 * Post a sale transaction to the General Ledger.
 *
 * Journal Entry:
 * DR Cash/AR (1010/1100)     $totalAmount (split by payment method)
 *     CR Sales Revenue (4000)    $subtotal
 *     CR Sales Tax Payable (2100) $taxAmount
 *     CR COD Charges Payable (2150) $codCharges (if COD payment)
 * DR COGS (5000)             $totalCOGS
 *     CR Inventory (1200)        $totalCOGS
 */
export async function postSaleToGL(
  sale: Sale,
  saleItems: Array<{ costPrice: number; quantity: number }>,
  userId: number,
  payments?: PaymentBreakdownForGL[],
  codCharges?: number
): Promise<number> {
  const lines: JournalLine[] = []

  const receivableAmount = sale.totalAmount - sale.amountPaid

  // DR Cash for amount paid - use payment breakdown if available
  if (payments && payments.length > 0) {
    // Mixed/split payment - create separate entries for each payment method
    for (const payment of payments) {
      if (payment.amount <= 0) continue

      // Determine account based on payment method
      const accountCode = ['card', 'debit_card', 'mobile', 'cheque', 'bank_transfer'].includes(payment.method)
        ? ACCOUNT_CODES.CASH_IN_BANK
        : ACCOUNT_CODES.CASH_IN_HAND

      const methodLabel = payment.method === 'card' ? 'Card'
        : payment.method === 'debit_card' ? 'Debit Card'
        : payment.method === 'mobile' ? 'Mobile'
        : payment.method === 'cheque' ? 'Cheque'
        : payment.method === 'bank_transfer' ? 'Bank Transfer'
        : payment.method === 'cod' ? 'COD'
        : 'Cash'

      lines.push({
        accountCode,
        debitAmount: payment.amount,
        creditAmount: 0,
        description: `${methodLabel} payment for sale ${sale.invoiceNumber}${payment.referenceNumber ? ` (Ref: ${payment.referenceNumber})` : ''}`,
      })
    }
  } else if (sale.amountPaid > 0) {
    // Single payment - use old logic
    // Debit only the net cash retained (amountPaid minus change given back)
    const netCashReceived = sale.amountPaid - (sale.changeGiven || 0)
    const cashAccountCode = sale.paymentMethod === 'card' || sale.paymentMethod === 'mobile'
      ? ACCOUNT_CODES.CASH_IN_BANK
      : ACCOUNT_CODES.CASH_IN_HAND

    if (netCashReceived > 0) {
      lines.push({
        accountCode: cashAccountCode,
        debitAmount: netCashReceived,
        creditAmount: 0,
        description: `Cash received for sale ${sale.invoiceNumber}`,
      })
    }
  }

  // DR Accounts Receivable for outstanding amount
  if (receivableAmount > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.ACCOUNTS_RECEIVABLE,
      debitAmount: receivableAmount,
      creditAmount: 0,
      description: `Receivable for sale ${sale.invoiceNumber}`,
    })
  }

  // CR Sales Revenue (net of tax)
  const netRevenue = sale.subtotal - sale.discountAmount
  if (netRevenue > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_REVENUE,
      debitAmount: 0,
      creditAmount: netRevenue,
      description: `Revenue from sale ${sale.invoiceNumber}`,
    })
  }

  // CR Sales Tax Payable
  if (sale.taxAmount > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_TAX_PAYABLE,
      debitAmount: 0,
      creditAmount: sale.taxAmount,
      description: `Sales tax for sale ${sale.invoiceNumber}`,
    })
  }

  // CR COD Charges Payable (liability until paid to courier)
  if (codCharges && codCharges > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.COD_CHARGES_PAYABLE,
      debitAmount: 0,
      creditAmount: codCharges,
      description: `COD charges collected for sale ${sale.invoiceNumber}`,
    })
  }

  // Calculate total COGS
  const totalCOGS = saleItems.reduce(
    (sum, item) => sum + item.costPrice * item.quantity,
    0
  )

  // DR COGS
  if (totalCOGS > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.COGS,
      debitAmount: totalCOGS,
      creditAmount: 0,
      description: `Cost of goods sold for ${sale.invoiceNumber}`,
    })

    // CR Inventory
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: 0,
      creditAmount: totalCOGS,
      description: `Inventory reduction for ${sale.invoiceNumber}`,
    })
  }

  return createJournalEntry({
    description: `Sale: ${sale.invoiceNumber}`,
    referenceType: 'sale',
    referenceId: sale.id,
    branchId: sale.branchId,
    userId,
    lines,
  })
}

/**
 * Post a purchase receive to the General Ledger.
 *
 * Journal Entry:
 * DR Inventory (1200)        $totalValue
 *     CR Accounts Payable (2000)  $totalValue  (if pay_later)
 *     OR CR Cash (1010)           $totalValue  (if paid)
 */
export async function postPurchaseReceiveToGL(
  purchase: Purchase,
  receivedItems: Array<{ unitCost: number; receivedQuantity: number }>,
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  // Calculate total value of received items
  const totalValue = receivedItems.reduce(
    (sum, item) => sum + item.unitCost * item.receivedQuantity,
    0
  )

  if (totalValue <= 0) {
    throw new Error('Cannot post zero-value purchase to GL')
  }

  // DR Inventory
  lines.push({
    accountCode: ACCOUNT_CODES.INVENTORY,
    debitAmount: totalValue,
    creditAmount: 0,
    description: `Inventory received for PO ${purchase.purchaseOrderNumber}`,
  })

  // CR based on payment method
  if (purchase.paymentMethod === 'pay_later' || purchase.paymentStatus === 'pending') {
    lines.push({
      accountCode: ACCOUNT_CODES.ACCOUNTS_PAYABLE,
      debitAmount: 0,
      creditAmount: totalValue,
      description: `Payable for PO ${purchase.purchaseOrderNumber}`,
    })
  } else {
    const cashAccount = purchase.paymentMethod === 'cheque'
      ? ACCOUNT_CODES.CASH_IN_BANK
      : ACCOUNT_CODES.CASH_IN_HAND
    lines.push({
      accountCode: cashAccount,
      debitAmount: 0,
      creditAmount: totalValue,
      description: `Payment for PO ${purchase.purchaseOrderNumber}`,
    })
  }

  return createJournalEntry({
    description: `Purchase Receive: ${purchase.purchaseOrderNumber}`,
    referenceType: 'purchase',
    referenceId: purchase.id,
    branchId: purchase.branchId,
    userId,
    lines,
  })
}

/**
 * Post an expense to the General Ledger.
 *
 * Journal Entry:
 * DR Expense Account (51xx)  $amount
 *     CR Cash (1010)             $amount  (if paid)
 *     OR CR AP (2000)            $amount  (if unpaid)
 */
export async function postExpenseToGL(
  expense: {
    id: number
    branchId: number
    categoryName: string
    amount: number
    paymentStatus: string
    paymentMethod?: string
    description?: string
  },
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  // Map expense category name (case-insensitive) to account code
  const categoryToAccount: Record<string, string> = {
    salaries: ACCOUNT_CODES.SALARIES_WAGES,
    rent: ACCOUNT_CODES.RENT_EXPENSE,
    utilities: ACCOUNT_CODES.UTILITIES_EXPENSE,
    supplies: ACCOUNT_CODES.OTHER_EXPENSE,
    maintenance: ACCOUNT_CODES.OTHER_EXPENSE,
    marketing: ACCOUNT_CODES.OTHER_EXPENSE,
    other: ACCOUNT_CODES.OTHER_EXPENSE,
  }

  const expenseAccount = categoryToAccount[expense.categoryName.toLowerCase()] || ACCOUNT_CODES.OTHER_EXPENSE

  // DR Expense Account
  lines.push({
    accountCode: expenseAccount,
    debitAmount: expense.amount,
    creditAmount: 0,
    description: expense.description || `Expense: ${expense.categoryName}`,
  })

  // CR based on payment status
  if (expense.paymentStatus === 'unpaid') {
    lines.push({
      accountCode: ACCOUNT_CODES.ACCOUNTS_PAYABLE,
      debitAmount: 0,
      creditAmount: expense.amount,
      description: `Payable for expense ${expense.categoryName}`,
    })
  } else {
    const cashAccount = expense.paymentMethod === 'bank_transfer' || expense.paymentMethod === 'cheque'
      ? ACCOUNT_CODES.CASH_IN_BANK
      : ACCOUNT_CODES.CASH_IN_HAND
    lines.push({
      accountCode: cashAccount,
      debitAmount: 0,
      creditAmount: expense.amount,
      description: `Payment for expense ${expense.categoryName}`,
    })
  }

  return createJournalEntry({
    description: `Expense: ${expense.categoryName}${expense.description ? ` - ${expense.description}` : ''}`,
    referenceType: 'expense',
    referenceId: expense.id,
    branchId: expense.branchId,
    userId,
    lines,
  })
}

/**
 * Post a return/refund to the General Ledger.
 * Reverses the original sale entries.
 *
 * Journal Entry:
 * DR Sales Revenue (4000)    $subtotal
 * DR Sales Tax Payable (2100) $taxAmount
 *     CR Cash/AR (1010/1100)     $totalAmount
 * DR Inventory (1200)        $totalCOGS  (if restockable)
 *     CR COGS (5000)             $totalCOGS
 */
export async function postReturnToGL(
  returnData: {
    id: number
    returnNumber: string
    branchId: number
    subtotal: number
    taxAmount: number
    totalAmount: number
    refundMethod?: string
  },
  returnItems: Array<{ costPrice: number; quantity: number; restockable: boolean }>,
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  // DR Sales Revenue (reverse the credit)
  const netRevenue = returnData.subtotal
  if (netRevenue > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_REVENUE,
      debitAmount: netRevenue,
      creditAmount: 0,
      description: `Revenue reversal for return ${returnData.returnNumber}`,
    })
  }

  // DR Sales Tax Payable (reverse the credit)
  if (returnData.taxAmount > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_TAX_PAYABLE,
      debitAmount: returnData.taxAmount,
      creditAmount: 0,
      description: `Tax reversal for return ${returnData.returnNumber}`,
    })
  }

  // CR Cash (refund given)
  const cashAccount = returnData.refundMethod === 'card'
    ? ACCOUNT_CODES.CASH_IN_BANK
    : ACCOUNT_CODES.CASH_IN_HAND
  lines.push({
    accountCode: cashAccount,
    debitAmount: 0,
    creditAmount: returnData.totalAmount,
    description: `Refund for return ${returnData.returnNumber}`,
  })

  // Calculate COGS for restockable items
  const restockableCOGS = returnItems
    .filter((item) => item.restockable)
    .reduce((sum, item) => sum + item.costPrice * item.quantity, 0)

  // DR Inventory, CR COGS for restockable items
  if (restockableCOGS > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: restockableCOGS,
      creditAmount: 0,
      description: `Inventory restored for return ${returnData.returnNumber}`,
    })
    lines.push({
      accountCode: ACCOUNT_CODES.COGS,
      debitAmount: 0,
      creditAmount: restockableCOGS,
      description: `COGS reversal for return ${returnData.returnNumber}`,
    })
  }

  return createJournalEntry({
    description: `Return: ${returnData.returnNumber}`,
    referenceType: 'return',
    referenceId: returnData.id,
    branchId: returnData.branchId,
    userId,
    lines,
  })
}

/**
 * Post an AR payment to the General Ledger.
 *
 * Journal Entry:
 * DR Cash (1010/1020)        $amount
 *     CR Accounts Receivable (1100) $amount
 */
export async function postARPaymentToGL(
  payment: {
    id: number
    receivableId: number
    branchId: number
    amount: number
    paymentMethod: string
    invoiceNumber: string
  },
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  const cashAccount = payment.paymentMethod === 'card' || payment.paymentMethod === 'bank_transfer' || payment.paymentMethod === 'mobile'
    ? ACCOUNT_CODES.CASH_IN_BANK
    : ACCOUNT_CODES.CASH_IN_HAND

  // DR Cash
  lines.push({
    accountCode: cashAccount,
    debitAmount: payment.amount,
    creditAmount: 0,
    description: `Payment received for ${payment.invoiceNumber}`,
  })

  // CR Accounts Receivable
  lines.push({
    accountCode: ACCOUNT_CODES.ACCOUNTS_RECEIVABLE,
    debitAmount: 0,
    creditAmount: payment.amount,
    description: `AR reduction for ${payment.invoiceNumber}`,
  })

  return createJournalEntry({
    description: `AR Payment: ${payment.invoiceNumber}`,
    referenceType: 'receivable_payment',
    referenceId: payment.id,
    branchId: payment.branchId,
    userId,
    lines,
  })
}

/**
 * Post an AP payment to the General Ledger.
 *
 * Journal Entry:
 * DR Accounts Payable (2000) $amount
 *     CR Cash (1010/1020)        $amount
 */
export async function postAPPaymentToGL(
  payment: {
    id: number
    payableId: number
    branchId: number
    amount: number
    paymentMethod: string
    invoiceNumber: string
  },
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  const cashAccount = payment.paymentMethod === 'bank_transfer' || payment.paymentMethod === 'cheque'
    ? ACCOUNT_CODES.CASH_IN_BANK
    : ACCOUNT_CODES.CASH_IN_HAND

  // DR Accounts Payable
  lines.push({
    accountCode: ACCOUNT_CODES.ACCOUNTS_PAYABLE,
    debitAmount: payment.amount,
    creditAmount: 0,
    description: `AP payment for ${payment.invoiceNumber}`,
  })

  // CR Cash
  lines.push({
    accountCode: cashAccount,
    debitAmount: 0,
    creditAmount: payment.amount,
    description: `Payment for ${payment.invoiceNumber}`,
  })

  return createJournalEntry({
    description: `AP Payment: ${payment.invoiceNumber}`,
    referenceType: 'payable_payment',
    referenceId: payment.id,
    branchId: payment.branchId,
    userId,
    lines,
  })
}

/**
 * Create a reversing journal entry for voided sales.
 */
export async function postVoidSaleToGL(
  sale: Sale,
  saleItems: Array<{ costPrice: number; quantity: number }>,
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  // Reverse the original entry - swap debits and credits
  const cashAccountCode = sale.paymentMethod === 'card' || sale.paymentMethod === 'mobile'
    ? ACCOUNT_CODES.CASH_IN_BANK
    : ACCOUNT_CODES.CASH_IN_HAND

  // CR Cash for amount paid (reverse the debit)
  if (sale.amountPaid > 0) {
    lines.push({
      accountCode: cashAccountCode,
      debitAmount: 0,
      creditAmount: sale.amountPaid,
      description: `Void - reverse cash for sale ${sale.invoiceNumber}`,
    })
  }

  // CR Accounts Receivable for outstanding amount (reverse the debit)
  const receivableAmount = sale.totalAmount - sale.amountPaid
  if (receivableAmount > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.ACCOUNTS_RECEIVABLE,
      debitAmount: 0,
      creditAmount: receivableAmount,
      description: `Void - reverse receivable for sale ${sale.invoiceNumber}`,
    })
  }

  // DR Sales Revenue (reverse the credit)
  const netRevenue = sale.subtotal - sale.discountAmount
  if (netRevenue > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_REVENUE,
      debitAmount: netRevenue,
      creditAmount: 0,
      description: `Void - reverse revenue from sale ${sale.invoiceNumber}`,
    })
  }

  // DR Sales Tax Payable (reverse the credit)
  if (sale.taxAmount > 0) {
    lines.push({
      accountCode: ACCOUNT_CODES.SALES_TAX_PAYABLE,
      debitAmount: sale.taxAmount,
      creditAmount: 0,
      description: `Void - reverse sales tax for sale ${sale.invoiceNumber}`,
    })
  }

  // DR COD Charges Payable (reverse the credit)
  // COD charges = totalAmount - (subtotal - discount + tax)
  const codCharges = sale.totalAmount - ((sale.subtotal - sale.discountAmount) + sale.taxAmount)
  if (codCharges > 0.01) {
    lines.push({
      accountCode: ACCOUNT_CODES.COD_CHARGES_PAYABLE,
      debitAmount: codCharges,
      creditAmount: 0,
      description: `Void - reverse COD charges for sale ${sale.invoiceNumber}`,
    })
  }

  // Calculate total COGS
  const totalCOGS = saleItems.reduce(
    (sum, item) => sum + item.costPrice * item.quantity,
    0
  )

  // Reverse COGS entries
  if (totalCOGS > 0) {
    // CR COGS (reverse the debit)
    lines.push({
      accountCode: ACCOUNT_CODES.COGS,
      debitAmount: 0,
      creditAmount: totalCOGS,
      description: `Void - reverse COGS for ${sale.invoiceNumber}`,
    })

    // DR Inventory (reverse the credit)
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: totalCOGS,
      creditAmount: 0,
      description: `Void - restore inventory for ${sale.invoiceNumber}`,
    })
  }

  return createJournalEntry({
    description: `Void Sale: ${sale.invoiceNumber}`,
    referenceType: 'sale_void',
    referenceId: sale.id,
    branchId: sale.branchId,
    userId,
    lines,
  })
}

/**
 * Post a stock adjustment to the General Ledger.
 *
 * For inventory reduction (damage/theft/loss):
 * DR Inventory Shrinkage (5400)  $value
 *     CR Inventory (1200)            $value
 *
 * For inventory addition:
 *   fundingSource = 'owner_capital':  DR Inventory / CR Owner's Capital (3000)
 *   fundingSource = 'accounts_payable': DR Inventory / CR Accounts Payable (2000)
 *   fundingSource = 'surplus' (default): DR Inventory / CR Inventory Adjustment Income (4900)
 */
export async function postStockAdjustmentToGL(
  adjustment: {
    id: number
    branchId: number
    adjustmentType: 'add' | 'remove' | 'damage' | 'theft' | 'correction' | 'expired'
    quantityChange: number
    unitCost: number
    reason: string
    reference?: string
    fundingSource?: 'owner_capital' | 'accounts_payable' | 'surplus'
    productName?: string
    quantityBefore?: number
    quantityAfter?: number
  },
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []
  const totalValue = Math.abs(adjustment.quantityChange) * adjustment.unitCost

  if (totalValue <= 0) {
    throw new Error('Cannot post zero-value adjustment to GL')
  }

  // Build detailed description with product info
  const productInfo = adjustment.productName ? `${adjustment.productName}` : 'Unknown product'
  const qtyInfo = adjustment.quantityBefore !== undefined && adjustment.quantityAfter !== undefined
    ? ` (${adjustment.quantityBefore} → ${adjustment.quantityAfter} units)`
    : ` (${Math.abs(adjustment.quantityChange)} units)`
  const detail = `${productInfo}${qtyInfo}`

  // Shrinkage types: actual loss that should hit the expense account
  const isShrinkage = ['damage', 'theft', 'expired'].includes(adjustment.adjustmentType)
  // Administrative removal: cleaning up records, not actual loss
  const isAdminRemoval = adjustment.adjustmentType === 'remove'
  // Correction: cycle count or manual correction
  const isCorrection = adjustment.adjustmentType === 'correction'
  // Addition
  const isAddition = adjustment.adjustmentType === 'add'

  if (isShrinkage) {
    // Actual loss/damage/theft/expiry: DR Shrinkage Expense, CR Inventory
    const typeLabel = adjustment.adjustmentType === 'damage' ? 'Damaged'
      : adjustment.adjustmentType === 'theft' ? 'Stolen'
      : 'Expired'
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY_SHRINKAGE,
      debitAmount: totalValue,
      creditAmount: 0,
      description: `${typeLabel} inventory: ${detail} - ${adjustment.reason}`,
    })
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: 0,
      creditAmount: totalValue,
      description: `Inventory write-off: ${detail}`,
    })
  } else if (isAdminRemoval) {
    // Administrative removal (record cleanup): DR Owner's Capital, CR Inventory
    // This is NOT an expense — it reverses the equity that funded the inventory
    lines.push({
      accountCode: ACCOUNT_CODES.OWNERS_CAPITAL,
      debitAmount: totalValue,
      creditAmount: 0,
      description: `Inventory removed: ${detail} - ${adjustment.reason}`,
    })
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: 0,
      creditAmount: totalValue,
      description: `Inventory reduction: ${detail}`,
    })
  } else if (isCorrection) {
    // Cycle count correction: variance can be positive or negative
    if (adjustment.quantityChange < 0) {
      // Shortage found: DR Shrinkage Expense, CR Inventory
      lines.push({
        accountCode: ACCOUNT_CODES.INVENTORY_SHRINKAGE,
        debitAmount: totalValue,
        creditAmount: 0,
        description: `Cycle count shortage: ${detail} - ${adjustment.reason}`,
      })
      lines.push({
        accountCode: ACCOUNT_CODES.INVENTORY,
        debitAmount: 0,
        creditAmount: totalValue,
        description: `Inventory correction (shortage): ${detail}`,
      })
    } else {
      // Surplus found: DR Inventory, CR Inventory Adjustment Income
      lines.push({
        accountCode: ACCOUNT_CODES.INVENTORY,
        debitAmount: totalValue,
        creditAmount: 0,
        description: `Inventory correction (surplus): ${detail}`,
      })
      lines.push({
        accountCode: ACCOUNT_CODES.INVENTORY_ADJUSTMENT,
        debitAmount: 0,
        creditAmount: totalValue,
        description: `Cycle count surplus: ${detail} - ${adjustment.reason}`,
      })
    }
  } else if (isAddition) {
    // Addition: DR Inventory
    lines.push({
      accountCode: ACCOUNT_CODES.INVENTORY,
      debitAmount: totalValue,
      creditAmount: 0,
      description: `Inventory added: ${detail} - ${adjustment.reason}`,
    })

    // CR based on funding source
    let creditAccount: string
    let creditDescription: string

    switch (adjustment.fundingSource) {
      case 'owner_capital':
        creditAccount = ACCOUNT_CODES.OWNERS_CAPITAL
        creditDescription = `Owner capital investment: ${detail}`
        break
      case 'accounts_payable':
        creditAccount = ACCOUNT_CODES.ACCOUNTS_PAYABLE
        creditDescription = `Supplier payable: ${detail}`
        break
      case 'surplus':
      default:
        creditAccount = ACCOUNT_CODES.INVENTORY_ADJUSTMENT
        creditDescription = `Inventory adjustment income: ${detail}`
        break
    }

    lines.push({
      accountCode: creditAccount,
      debitAmount: 0,
      creditAmount: totalValue,
      description: creditDescription,
    })
  }

  const typeLabels: Record<string, string> = {
    add: 'Addition',
    remove: 'Removal',
    damage: 'Damage Write-off',
    theft: 'Theft Write-off',
    correction: 'Cycle Count Correction',
    expired: 'Expiry Write-off',
  }

  return createJournalEntry({
    description: `Stock ${typeLabels[adjustment.adjustmentType] || adjustment.adjustmentType}: ${detail} - ${adjustment.reason}`,
    referenceType: 'stock_adjustment',
    referenceId: adjustment.id,
    branchId: adjustment.branchId,
    userId,
    lines,
  })
}

/**
 * Post a commission payment to the General Ledger.
 *
 * Journal Entry:
 * DR Commission Expense (5900)  $amount
 *     CR Cash (1010/1020)           $amount
 */
export async function postCommissionPaymentToGL(
  commission: {
    id: number
    branchId: number
    commissionAmount: number
    commissionType: string
    saleId: number
  },
  userId: number
): Promise<number> {
  const lines: JournalLine[] = []

  // DR Commission Expense
  lines.push({
    accountCode: ACCOUNT_CODES.OTHER_EXPENSE,
    debitAmount: commission.commissionAmount,
    creditAmount: 0,
    description: `Commission payment: ${commission.commissionType} for sale #${commission.saleId}`,
  })

  // CR Cash in Hand (commissions are typically paid in cash)
  lines.push({
    accountCode: ACCOUNT_CODES.CASH_IN_HAND,
    debitAmount: 0,
    creditAmount: commission.commissionAmount,
    description: `Cash paid for commission #${commission.id}`,
  })

  return createJournalEntry({
    description: `Commission Payment: ${commission.commissionType} commission #${commission.id}`,
    referenceType: 'commission',
    referenceId: commission.id,
    branchId: commission.branchId,
    userId,
    lines,
  })
}
