'use server'

import { db } from '@/lib/db'
import {
  journalEntries,
  journalEntryLines,
  chartOfAccounts,
} from '@/lib/db/schema'
import { eq, and, sql, count } from 'drizzle-orm'

/**
 * Generate the next journal entry number for a tenant: JE-YYYY-NNNN
 */
async function nextEntryNumber(tenantId: number): Promise<string> {
  const year = new Date().getFullYear()
  const [result] = await db
    .select({ c: count() })
    .from(journalEntries)
    .where(
      and(
        eq(journalEntries.tenantId, tenantId),
        sql`EXTRACT(YEAR FROM ${journalEntries.entryDate}) = ${year}`
      )
    )
  const seq = String((result.c || 0) + 1).padStart(4, '0')
  return `JE-${year}-${seq}`
}

/**
 * Find a GL account by sub-type for a tenant. Returns null if not found.
 */
async function findAccount(tenantId: number, subType: string) {
  const [account] = await db
    .select()
    .from(chartOfAccounts)
    .where(
      and(
        eq(chartOfAccounts.tenantId, tenantId),
        eq(chartOfAccounts.accountSubType, subType),
        eq(chartOfAccounts.isActive, true)
      )
    )
    .limit(1)
  return account
}

async function findAccountByType(tenantId: number, accountType: string) {
  const [account] = await db
    .select()
    .from(chartOfAccounts)
    .where(
      and(
        eq(chartOfAccounts.tenantId, tenantId),
        eq(chartOfAccounts.accountType, accountType as any),
        eq(chartOfAccounts.isActive, true)
      )
    )
    .limit(1)
  return account
}

interface GLLine {
  accountId: number
  debitAmount: string
  creditAmount: string
  description?: string
}

/**
 * Create and auto-post a journal entry with the given lines.
 */
async function createAndPostEntry(params: {
  tenantId: number
  description: string
  referenceType: string
  referenceId: number
  branchId: number
  userId: number
  lines: GLLine[]
}) {
  const entryNumber = await nextEntryNumber(params.tenantId)

  const [entry] = await db
    .insert(journalEntries)
    .values({
      tenantId: params.tenantId,
      entryNumber,
      entryDate: new Date(),
      description: params.description,
      referenceType: params.referenceType,
      referenceId: params.referenceId,
      branchId: params.branchId,
      status: 'posted',
      isAutoGenerated: true,
      createdBy: params.userId,
      postedBy: params.userId,
      postedAt: new Date(),
    })
    .returning()

  if (params.lines.length > 0) {
    await db.insert(journalEntryLines).values(
      params.lines.map((line) => ({
        journalEntryId: entry.id,
        accountId: line.accountId,
        debitAmount: line.debitAmount,
        creditAmount: line.creditAmount,
        description: line.description || null,
      }))
    )
  }

  // Update account balances
  for (const line of params.lines) {
    const debit = Number(line.debitAmount) || 0
    const credit = Number(line.creditAmount) || 0
    const net = debit - credit

    await db
      .update(chartOfAccounts)
      .set({
        currentBalance: sql`${chartOfAccounts.currentBalance}::numeric + ${net}`,
        updatedAt: new Date(),
      })
      .where(eq(chartOfAccounts.id, line.accountId))
  }

  return entry
}

/**
 * Post a sale to GL: Debit Cash/AR, Credit Revenue + Tax Payable
 */
export async function postSaleToGL(params: {
  tenantId: number
  saleId: number
  branchId: number
  userId: number
  totalAmount: number
  taxAmount: number
  costOfGoods: number
  paymentMethod: string
}) {
  const lines: GLLine[] = []

  // Debit: Cash or AR
  const isCredit = ['credit', 'receivable'].includes(params.paymentMethod)
  const debitAccount = isCredit
    ? await findAccount(params.tenantId, 'accounts_receivable')
    : await findAccount(params.tenantId, 'cash')

  if (debitAccount) {
    lines.push({
      accountId: debitAccount.id,
      debitAmount: String(params.totalAmount),
      creditAmount: '0',
      description: isCredit ? 'Accounts receivable from sale' : 'Cash received from sale',
    })
  }

  // Credit: Revenue
  const revenueAccount =
    (await findAccount(params.tenantId, 'sales_revenue')) ||
    (await findAccountByType(params.tenantId, 'revenue'))
  if (revenueAccount) {
    const revenueAmount = params.totalAmount - params.taxAmount
    lines.push({
      accountId: revenueAccount.id,
      debitAmount: '0',
      creditAmount: String(revenueAmount),
      description: 'Sales revenue',
    })
  }

  // Credit: Tax payable (if tax > 0)
  if (params.taxAmount > 0) {
    const taxAccount = await findAccount(params.tenantId, 'accrued_expense')
    if (taxAccount) {
      lines.push({
        accountId: taxAccount.id,
        debitAmount: '0',
        creditAmount: String(params.taxAmount),
        description: 'Tax collected on sale',
      })
    }
  }

  // COGS entry: Debit COGS, Credit Inventory
  if (params.costOfGoods > 0) {
    const cogsAccount = await findAccount(params.tenantId, 'cost_of_goods_sold')
    const inventoryAccount = await findAccount(params.tenantId, 'inventory')

    if (cogsAccount) {
      lines.push({
        accountId: cogsAccount.id,
        debitAmount: String(params.costOfGoods),
        creditAmount: '0',
        description: 'Cost of goods sold',
      })
    }
    if (inventoryAccount) {
      lines.push({
        accountId: inventoryAccount.id,
        debitAmount: '0',
        creditAmount: String(params.costOfGoods),
        description: 'Inventory reduction for sale',
      })
    }
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `Sale #${params.saleId}`,
    referenceType: 'sale',
    referenceId: params.saleId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Reverse a sale GL entry (void/return)
 */
export async function postReturnToGL(params: {
  tenantId: number
  returnId: number
  originalSaleId: number
  branchId: number
  userId: number
  refundAmount: number
  taxAmount: number
  costOfGoods: number
  refundMethod: string
}) {
  const lines: GLLine[] = []

  // Credit Cash/AR (refund out)
  const isCreditRefund = params.refundMethod === 'store_credit'
  const cashAccount = isCreditRefund
    ? await findAccount(params.tenantId, 'accounts_receivable')
    : await findAccount(params.tenantId, 'cash')

  if (cashAccount) {
    lines.push({
      accountId: cashAccount.id,
      debitAmount: '0',
      creditAmount: String(params.refundAmount),
      description: 'Refund issued',
    })
  }

  // Debit Revenue (reverse)
  const revenueAccount =
    (await findAccount(params.tenantId, 'sales_revenue')) ||
    (await findAccountByType(params.tenantId, 'revenue'))
  if (revenueAccount) {
    lines.push({
      accountId: revenueAccount.id,
      debitAmount: String(params.refundAmount - params.taxAmount),
      creditAmount: '0',
      description: 'Revenue reversal for return',
    })
  }

  // Debit Tax payable (reverse)
  if (params.taxAmount > 0) {
    const taxAccount = await findAccount(params.tenantId, 'accrued_expense')
    if (taxAccount) {
      lines.push({
        accountId: taxAccount.id,
        debitAmount: String(params.taxAmount),
        creditAmount: '0',
        description: 'Tax reversal for return',
      })
    }
  }

  // Reverse COGS: Debit Inventory, Credit COGS
  if (params.costOfGoods > 0) {
    const cogsAccount = await findAccount(params.tenantId, 'cost_of_goods_sold')
    const inventoryAccount = await findAccount(params.tenantId, 'inventory')

    if (inventoryAccount) {
      lines.push({
        accountId: inventoryAccount.id,
        debitAmount: String(params.costOfGoods),
        creditAmount: '0',
        description: 'Inventory restored from return',
      })
    }
    if (cogsAccount) {
      lines.push({
        accountId: cogsAccount.id,
        debitAmount: '0',
        creditAmount: String(params.costOfGoods),
        description: 'COGS reversal for return',
      })
    }
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `Return #${params.returnId} (Sale #${params.originalSaleId})`,
    referenceType: 'return',
    referenceId: params.returnId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Post purchase receive to GL: Debit Inventory, Credit AP/Cash
 */
export async function postPurchaseToGL(params: {
  tenantId: number
  purchaseId: number
  branchId: number
  userId: number
  totalAmount: number
  paymentMethod: string
}) {
  const lines: GLLine[] = []

  // Debit: Inventory
  const inventoryAccount = await findAccount(params.tenantId, 'inventory')
  if (inventoryAccount) {
    lines.push({
      accountId: inventoryAccount.id,
      debitAmount: String(params.totalAmount),
      creditAmount: '0',
      description: 'Inventory received from purchase',
    })
  }

  // Credit: AP or Cash
  const isPayLater = params.paymentMethod === 'pay_later'
  const creditAccount = isPayLater
    ? await findAccount(params.tenantId, 'accounts_payable')
    : await findAccount(params.tenantId, 'cash')

  if (creditAccount) {
    lines.push({
      accountId: creditAccount.id,
      debitAmount: '0',
      creditAmount: String(params.totalAmount),
      description: isPayLater ? 'Accounts payable for purchase' : 'Cash paid for purchase',
    })
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `Purchase #${params.purchaseId}`,
    referenceType: 'purchase',
    referenceId: params.purchaseId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Post expense to GL: Debit Expense, Credit Cash/AP
 */
export async function postExpenseToGL(params: {
  tenantId: number
  expenseId: number
  branchId: number
  userId: number
  amount: number
  category: string
  paymentMethod: string
}) {
  const lines: GLLine[] = []

  // Debit: Expense account
  const expenseAccount =
    (await findAccount(params.tenantId, 'operating_expense')) ||
    (await findAccountByType(params.tenantId, 'expense'))
  if (expenseAccount) {
    lines.push({
      accountId: expenseAccount.id,
      debitAmount: String(params.amount),
      creditAmount: '0',
      description: `${params.category} expense`,
    })
  }

  // Credit: Cash
  const cashAccount = await findAccount(params.tenantId, 'cash')
  if (cashAccount) {
    lines.push({
      accountId: cashAccount.id,
      debitAmount: '0',
      creditAmount: String(params.amount),
      description: 'Cash paid for expense',
    })
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `Expense #${params.expenseId} - ${params.category}`,
    referenceType: 'expense',
    referenceId: params.expenseId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Post stock adjustment to GL: Debit Variance Expense, Credit Inventory (or reverse)
 */
export async function postStockAdjustmentToGL(params: {
  tenantId: number
  adjustmentId: number
  branchId: number
  userId: number
  amount: number
  isAddition: boolean
}) {
  const lines: GLLine[] = []

  const inventoryAccount = await findAccount(params.tenantId, 'inventory')
  const varianceAccount =
    (await findAccount(params.tenantId, 'other_expense')) ||
    (await findAccountByType(params.tenantId, 'expense'))

  if (params.isAddition) {
    // Adding stock: Debit Inventory, Credit Variance
    if (inventoryAccount) {
      lines.push({
        accountId: inventoryAccount.id,
        debitAmount: String(params.amount),
        creditAmount: '0',
        description: 'Inventory adjustment (add)',
      })
    }
    if (varianceAccount) {
      lines.push({
        accountId: varianceAccount.id,
        debitAmount: '0',
        creditAmount: String(params.amount),
        description: 'Stock variance adjustment',
      })
    }
  } else {
    // Removing stock: Debit Variance, Credit Inventory
    if (varianceAccount) {
      lines.push({
        accountId: varianceAccount.id,
        debitAmount: String(params.amount),
        creditAmount: '0',
        description: 'Stock variance (damage/theft/correction)',
      })
    }
    if (inventoryAccount) {
      lines.push({
        accountId: inventoryAccount.id,
        debitAmount: '0',
        creditAmount: String(params.amount),
        description: 'Inventory reduction from adjustment',
      })
    }
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `Stock Adjustment #${params.adjustmentId}`,
    referenceType: 'adjustment',
    referenceId: params.adjustmentId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Post receivable payment to GL: Debit Cash, Credit AR
 */
export async function postReceivablePaymentToGL(params: {
  tenantId: number
  receivableId: number
  paymentId: number
  branchId: number
  userId: number
  amount: number
}) {
  const lines: GLLine[] = []

  const cashAccount = await findAccount(params.tenantId, 'cash')
  const arAccount = await findAccount(params.tenantId, 'accounts_receivable')

  if (cashAccount) {
    lines.push({
      accountId: cashAccount.id,
      debitAmount: String(params.amount),
      creditAmount: '0',
      description: 'Cash received on receivable',
    })
  }
  if (arAccount) {
    lines.push({
      accountId: arAccount.id,
      debitAmount: '0',
      creditAmount: String(params.amount),
      description: 'AR reduced by payment',
    })
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `AR Payment #${params.paymentId} for Receivable #${params.receivableId}`,
    referenceType: 'ar_payment',
    referenceId: params.paymentId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}

/**
 * Post payable payment to GL: Debit AP, Credit Cash
 */
export async function postPayablePaymentToGL(params: {
  tenantId: number
  payableId: number
  paymentId: number
  branchId: number
  userId: number
  amount: number
}) {
  const lines: GLLine[] = []

  const apAccount = await findAccount(params.tenantId, 'accounts_payable')
  const cashAccount = await findAccount(params.tenantId, 'cash')

  if (apAccount) {
    lines.push({
      accountId: apAccount.id,
      debitAmount: String(params.amount),
      creditAmount: '0',
      description: 'AP reduced by payment',
    })
  }
  if (cashAccount) {
    lines.push({
      accountId: cashAccount.id,
      debitAmount: '0',
      creditAmount: String(params.amount),
      description: 'Cash paid on payable',
    })
  }

  if (lines.length === 0) return null

  return createAndPostEntry({
    tenantId: params.tenantId,
    description: `AP Payment #${params.paymentId} for Payable #${params.payableId}`,
    referenceType: 'ap_payment',
    referenceId: params.paymentId,
    branchId: params.branchId,
    userId: params.userId,
    lines,
  })
}
