'use client'

import { useState } from 'react'
import {
  FileText,
  Plus,
  Filter,
  CheckCircle2,
  Clock,
  RotateCcw,
  Eye,
  PlayCircle,
  XCircle,
} from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'

const mockEntries = [
  { id: 1, entryNumber: 'JE-001', entryDate: '2026-02-01', description: 'Opening balances', status: 'posted', isAutoGenerated: false, totalDebit: '500000', totalCredit: '500000' },
  { id: 2, entryNumber: 'JE-002', entryDate: '2026-02-02', description: 'Sale INV-0042 — Cash receipt', status: 'posted', isAutoGenerated: true, totalDebit: '45000', totalCredit: '45000' },
  { id: 3, entryNumber: 'JE-003', entryDate: '2026-02-03', description: 'Purchase PO-0018 — Ammunition stock', status: 'posted', isAutoGenerated: true, totalDebit: '120000', totalCredit: '120000' },
  { id: 4, entryNumber: 'JE-004', entryDate: '2026-02-04', description: 'Salary expense — February', status: 'draft', isAutoGenerated: false, totalDebit: '85000', totalCredit: '85000' },
  { id: 5, entryNumber: 'JE-005', entryDate: '2026-02-05', description: 'Reversed — duplicate entry', status: 'reversed', isAutoGenerated: false, totalDebit: '10000', totalCredit: '10000' },
]

const statusConfig: Record<string, { color: string; icon: typeof CheckCircle2 }> = {
  draft: { color: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20', icon: Clock },
  posted: { color: 'bg-success/10 text-success border-success/20', icon: CheckCircle2 },
  reversed: { color: 'bg-red-500/10 text-red-400 border-red-500/20', icon: RotateCcw },
}

const summaryCards = [
  { title: 'Total Entries', value: String(mockEntries.length), icon: FileText, accent: 'text-primary' },
  { title: 'Draft', value: String(mockEntries.filter((e) => e.status === 'draft').length), icon: Clock, accent: 'text-yellow-400' },
  { title: 'Posted', value: String(mockEntries.filter((e) => e.status === 'posted').length), icon: CheckCircle2, accent: 'text-success' },
  { title: 'Reversed', value: String(mockEntries.filter((e) => e.status === 'reversed').length), icon: RotateCcw, accent: 'text-red-400' },
]

export default function JournalEntriesPage() {
  const [filterStatus, setFilterStatus] = useState('all')

  const filtered = mockEntries.filter((e) => {
    if (filterStatus !== 'all' && e.status !== filterStatus) return false
    return true
  })

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Journal Entries</h1>
          <p className="text-sm text-muted-foreground mt-1">Record and manage double-entry transactions</p>
        </div>
        <Dialog>
          <DialogTrigger asChild>
            <Button className="brass-glow">
              <Plus className="w-4 h-4 mr-2" />
              New Entry
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[600px]">
            <DialogHeader>
              <DialogTitle>Create Journal Entry</DialogTitle>
            </DialogHeader>
            <form className="space-y-4 mt-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Entry Date</Label>
                  <Input type="date" />
                </div>
                <div className="space-y-2">
                  <Label>Description</Label>
                  <Input placeholder="Entry description" />
                </div>
              </div>
              <div className="border rounded-lg p-4 space-y-3">
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Entry Lines</p>
                <div className="grid grid-cols-12 gap-2 text-xs text-muted-foreground font-medium">
                  <div className="col-span-5">Account</div>
                  <div className="col-span-3 text-right">Debit</div>
                  <div className="col-span-3 text-right">Credit</div>
                  <div className="col-span-1"></div>
                </div>
                <div className="grid grid-cols-12 gap-2">
                  <div className="col-span-5">
                    <Select>
                      <SelectTrigger className="h-9 text-sm"><SelectValue placeholder="Select account" /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1000">1000 - Cash</SelectItem>
                        <SelectItem value="4000">4000 - Sales Revenue</SelectItem>
                        <SelectItem value="5000">5000 - COGS</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="col-span-3"><Input type="number" placeholder="0.00" className="h-9 text-sm text-right" /></div>
                  <div className="col-span-3"><Input type="number" placeholder="0.00" className="h-9 text-sm text-right" /></div>
                  <div className="col-span-1"></div>
                </div>
                <div className="grid grid-cols-12 gap-2">
                  <div className="col-span-5">
                    <Select>
                      <SelectTrigger className="h-9 text-sm"><SelectValue placeholder="Select account" /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1000">1000 - Cash</SelectItem>
                        <SelectItem value="4000">4000 - Sales Revenue</SelectItem>
                        <SelectItem value="5000">5000 - COGS</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="col-span-3"><Input type="number" placeholder="0.00" className="h-9 text-sm text-right" /></div>
                  <div className="col-span-3"><Input type="number" placeholder="0.00" className="h-9 text-sm text-right" /></div>
                  <div className="col-span-1"></div>
                </div>
                <Button variant="outline" size="sm" className="w-full">
                  <Plus className="w-3 h-3 mr-1" /> Add Line
                </Button>
              </div>
              <Button type="submit" className="w-full brass-glow">Save as Draft</Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {summaryCards.map((card) => (
          <Card key={card.title} className="card-tactical">
            <CardContent className="p-5">
              <div className="flex items-start justify-between">
                <div className="space-y-2">
                  <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{card.title}</p>
                  <p className="text-2xl font-bold tracking-tight">{card.value}</p>
                </div>
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  <card.icon className={`w-5 h-5 ${card.accent}`} />
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardContent className="p-4">
          <div className="flex items-center gap-3">
            <Filter className="w-4 h-4 text-muted-foreground" />
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[140px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="draft">Draft</SelectItem>
                <SelectItem value="posted">Posted</SelectItem>
                <SelectItem value="reversed">Reversed</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Entry #</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Description</TableHead>
                <TableHead className="text-right">Debit</TableHead>
                <TableHead className="text-right">Credit</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="w-[120px]"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((entry) => {
                const cfg = statusConfig[entry.status]
                return (
                  <TableRow key={entry.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <code className="text-sm font-bold font-mono bg-primary/10 text-primary px-2 py-0.5 rounded">
                          {entry.entryNumber}
                        </code>
                        {entry.isAutoGenerated && (
                          <span className="text-[10px] text-muted-foreground/60 uppercase">Auto</span>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">{entry.entryDate}</TableCell>
                    <TableCell className="text-sm font-medium">{entry.description}</TableCell>
                    <TableCell className="text-right text-sm font-semibold">Rs. {Number(entry.totalDebit).toLocaleString()}</TableCell>
                    <TableCell className="text-right text-sm font-semibold">Rs. {Number(entry.totalCredit).toLocaleString()}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className={`text-[10px] capitalize ${cfg.color}`}>
                        {entry.status}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button variant="ghost" size="icon" className="h-7 w-7" title="View">
                          <Eye className="w-3.5 h-3.5" />
                        </Button>
                        {entry.status === 'draft' && (
                          <Button variant="ghost" size="icon" className="h-7 w-7 text-success" title="Post">
                            <PlayCircle className="w-3.5 h-3.5" />
                          </Button>
                        )}
                        {entry.status === 'posted' && (
                          <Button variant="ghost" size="icon" className="h-7 w-7 text-red-400" title="Reverse">
                            <XCircle className="w-3.5 h-3.5" />
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                )
              })}
              {filtered.length === 0 && (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                    No journal entries found
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
