CREATE TABLE `business_settings` (
	`setting_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`branch_id` integer,
	`business_name` text NOT NULL,
	`business_registration_no` text,
	`business_type` text,
	`business_address` text,
	`business_city` text,
	`business_state` text,
	`business_country` text,
	`business_postal_code` text,
	`business_phone` text,
	`business_email` text,
	`business_website` text,
	`business_logo` text,
	`tax_id` text,
	`tax_rate` real DEFAULT 0,
	`tax_name` text DEFAULT 'GST',
	`is_tax_inclusive` integer DEFAULT false,
	`secondary_tax_rate` real DEFAULT 0,
	`secondary_tax_name` text,
	`currency_symbol` text DEFAULT 'Rs.',
	`currency_code` text DEFAULT 'PKR',
	`currency_position` text DEFAULT 'prefix',
	`decimal_places` integer DEFAULT 2,
	`thousand_separator` text DEFAULT ',',
	`decimal_separator` text DEFAULT '.',
	`receipt_header` text,
	`receipt_footer` text,
	`receipt_logo` text,
	`invoice_prefix` text DEFAULT 'INV',
	`invoice_number_format` text DEFAULT 'sequential',
	`invoice_starting_number` integer DEFAULT 1,
	`show_tax_on_receipt` integer DEFAULT true,
	`show_qr_code_on_receipt` integer DEFAULT false,
	`low_stock_threshold` integer DEFAULT 10,
	`enable_stock_tracking` integer DEFAULT true,
	`allow_negative_stock` integer DEFAULT false,
	`stock_valuation_method` text DEFAULT 'FIFO',
	`auto_reorder_enabled` integer DEFAULT false,
	`auto_reorder_quantity` integer DEFAULT 50,
	`default_payment_method` text DEFAULT 'Cash',
	`allowed_payment_methods` text DEFAULT 'Cash,Card,Bank Transfer,COD',
	`enable_cash_drawer` integer DEFAULT true,
	`opening_cash_balance` real DEFAULT 0,
	`enable_discounts` integer DEFAULT true,
	`max_discount_percentage` real DEFAULT 50,
	`require_customer_for_sale` integer DEFAULT false,
	`enable_customer_loyalty` integer DEFAULT false,
	`loyalty_points_ratio` real DEFAULT 1,
	`expense_categories` text DEFAULT 'Utilities,Rent,Salaries,Supplies,Maintenance,Other',
	`expense_approval_required` integer DEFAULT false,
	`expense_approval_limit` real DEFAULT 10000,
	`enable_returns` integer DEFAULT true,
	`return_window_days` integer DEFAULT 30,
	`require_receipt_for_return` integer DEFAULT true,
	`refund_method` text DEFAULT 'Original Payment Method',
	`enable_email_notifications` integer DEFAULT false,
	`notification_email` text,
	`low_stock_notifications` integer DEFAULT true,
	`daily_sales_report` integer DEFAULT false,
	`working_days_start` text DEFAULT 'Monday',
	`working_days_end` text DEFAULT 'Saturday',
	`opening_time` text DEFAULT '09:00',
	`closing_time` text DEFAULT '18:00',
	`auto_backup_enabled` integer DEFAULT true,
	`auto_backup_frequency` text DEFAULT 'daily',
	`backup_retention_days` integer DEFAULT 30,
	`date_format` text DEFAULT 'DD/MM/YYYY',
	`time_format` text DEFAULT '24-hour',
	`language` text DEFAULT 'en',
	`timezone` text DEFAULT 'UTC',
	`session_timeout_minutes` integer DEFAULT 60,
	`require_password_change` integer DEFAULT false,
	`password_change_interval_days` integer DEFAULT 90,
	`enable_audit_logs` integer DEFAULT true,
	`is_active` integer DEFAULT true,
	`is_default` integer DEFAULT false,
	`notes` text,
	`created_by` integer,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `business_settings_branch_id_idx` ON `business_settings` (`branch_id`);
--> statement-breakpoint
CREATE INDEX `business_settings_created_by_idx` ON `business_settings` (`created_by`);
