import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core'
import { relations } from 'drizzle-orm'
import { branches } from './branches'
import { users } from './users'

// Chart of Accounts - master list of all accounts
export const chartOfAccounts = sqliteTable(
  'chart_of_accounts',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    accountCode: text('account_code').notNull().unique(), // e.g., "1000", "1100", "2000"
    accountName: text('account_name').notNull(),
    accountType: text('account_type', {
      enum: ['asset', 'liability', 'equity', 'revenue', 'expense'],
    }).notNull(),
    accountSubType: text('account_sub_type', {
      enum: [
        // Assets
        'cash',
        'bank',
        'accounts_receivable',
        'inventory',
        'prepaid_expense',
        'fixed_asset',
        'accumulated_depreciation',
        'other_asset',
        // Liabilities
        'accounts_payable',
        'accrued_expense',
        'short_term_loan',
        'long_term_loan',
        'other_liability',
        // Equity
        'owner_capital',
        'retained_earnings',
        'drawings',
        // Revenue
        'sales_revenue',
        'service_revenue',
        'other_revenue',
        // Expenses
        'cost_of_goods_sold',
        'operating_expense',
        'payroll_expense',
        'rent_expense',
        'utilities_expense',
        'depreciation_expense',
        'other_expense',
      ],
    }),
    parentAccountId: integer('parent_account_id'), // For hierarchical accounts
    description: text('description'),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    isSystemAccount: integer('is_system_account', { mode: 'boolean' }).notNull().default(false), // Cannot be deleted
    normalBalance: text('normal_balance', { enum: ['debit', 'credit'] }).notNull(),
    currentBalance: real('current_balance').notNull().default(0),
    createdAt: text('created_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
    updatedAt: text('updated_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    typeIdx: index('coa_type_idx').on(table.accountType),
    parentIdx: index('coa_parent_idx').on(table.parentAccountId),
    activeIdx: index('coa_active_idx').on(table.isActive),
  })
)

// Journal Entries - double-entry accounting records
export const journalEntries = sqliteTable(
  'journal_entries',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    entryNumber: text('entry_number').notNull().unique(), // JE-YYYY-NNNN
    entryDate: text('entry_date').notNull(),
    description: text('description').notNull(),
    referenceType: text('reference_type'), // 'sale', 'purchase', 'expense', 'adjustment', etc.
    referenceId: integer('reference_id'),
    branchId: integer('branch_id').references(() => branches.id),
    status: text('status', { enum: ['draft', 'posted', 'reversed'] })
      .notNull()
      .default('draft'),
    isAutoGenerated: integer('is_auto_generated', { mode: 'boolean' }).notNull().default(false),
    createdBy: integer('created_by')
      .notNull()
      .references(() => users.id),
    postedBy: integer('posted_by').references(() => users.id),
    postedAt: text('posted_at'),
    reversedBy: integer('reversed_by').references(() => users.id),
    reversedAt: text('reversed_at'),
    reversalEntryId: integer('reversal_entry_id'), // Links to the reversing entry
    createdAt: text('created_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
    updatedAt: text('updated_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    dateIdx: index('je_date_idx').on(table.entryDate),
    statusIdx: index('je_status_idx').on(table.status),
    refIdx: index('je_ref_idx').on(table.referenceType, table.referenceId),
  })
)

// Journal Entry Lines - individual debit/credit entries
export const journalEntryLines = sqliteTable(
  'journal_entry_lines',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    journalEntryId: integer('journal_entry_id')
      .notNull()
      .references(() => journalEntries.id, { onDelete: 'cascade' }),
    accountId: integer('account_id')
      .notNull()
      .references(() => chartOfAccounts.id),
    debitAmount: real('debit_amount').notNull().default(0),
    creditAmount: real('credit_amount').notNull().default(0),
    description: text('description'),
    createdAt: text('created_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    entryIdx: index('jel_entry_idx').on(table.journalEntryId),
    accountIdx: index('jel_account_idx').on(table.accountId),
  })
)

// Account Balances - periodic balance snapshots for reporting
export const accountBalances = sqliteTable(
  'account_balances',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    accountId: integer('account_id')
      .notNull()
      .references(() => chartOfAccounts.id),
    branchId: integer('branch_id').references(() => branches.id), // null for consolidated
    periodType: text('period_type', { enum: ['daily', 'monthly', 'yearly'] }).notNull(),
    periodDate: text('period_date').notNull(), // YYYY-MM-DD for daily, YYYY-MM for monthly, YYYY for yearly
    openingBalance: real('opening_balance').notNull().default(0),
    debitTotal: real('debit_total').notNull().default(0),
    creditTotal: real('credit_total').notNull().default(0),
    closingBalance: real('closing_balance').notNull().default(0),
    createdAt: text('created_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
    updatedAt: text('updated_at')
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    accountPeriodIdx: index('ab_account_period_idx').on(table.accountId, table.periodType, table.periodDate),
    branchIdx: index('ab_branch_idx').on(table.branchId),
  })
)

// Relations
export const chartOfAccountsRelations = relations(chartOfAccounts, ({ one, many }) => ({
  parentAccount: one(chartOfAccounts, {
    fields: [chartOfAccounts.parentAccountId],
    references: [chartOfAccounts.id],
    relationName: 'parentChild',
  }),
  childAccounts: many(chartOfAccounts, { relationName: 'parentChild' }),
  journalLines: many(journalEntryLines),
  balances: many(accountBalances),
}))

export const journalEntriesRelations = relations(journalEntries, ({ one, many }) => ({
  branch: one(branches, {
    fields: [journalEntries.branchId],
    references: [branches.id],
  }),
  createdByUser: one(users, {
    fields: [journalEntries.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
  postedByUser: one(users, {
    fields: [journalEntries.postedBy],
    references: [users.id],
    relationName: 'postedBy',
  }),
  lines: many(journalEntryLines),
}))

export const journalEntryLinesRelations = relations(journalEntryLines, ({ one }) => ({
  journalEntry: one(journalEntries, {
    fields: [journalEntryLines.journalEntryId],
    references: [journalEntries.id],
  }),
  account: one(chartOfAccounts, {
    fields: [journalEntryLines.accountId],
    references: [chartOfAccounts.id],
  }),
}))

export const accountBalancesRelations = relations(accountBalances, ({ one }) => ({
  account: one(chartOfAccounts, {
    fields: [accountBalances.accountId],
    references: [chartOfAccounts.id],
  }),
  branch: one(branches, {
    fields: [accountBalances.branchId],
    references: [branches.id],
  }),
}))

export type ChartOfAccount = typeof chartOfAccounts.$inferSelect
export type NewChartOfAccount = typeof chartOfAccounts.$inferInsert
export type JournalEntry = typeof journalEntries.$inferSelect
export type NewJournalEntry = typeof journalEntries.$inferInsert
export type JournalEntryLine = typeof journalEntryLines.$inferSelect
export type NewJournalEntryLine = typeof journalEntryLines.$inferInsert
export type AccountBalance = typeof accountBalances.$inferSelect
export type NewAccountBalance = typeof accountBalances.$inferInsert
