import {
  pgTable,
  serial,
  text,
  boolean,
  timestamp,
  integer,
  numeric,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { tenants } from './tenants'
import { branches } from './branches'
import { users } from './users'

export const chartOfAccounts = pgTable(
  'chart_of_accounts',
  {
    id: serial('id').primaryKey(),
    tenantId: integer('tenant_id')
      .notNull()
      .references(() => tenants.id),
    accountCode: text('account_code').notNull(),
    accountName: text('account_name').notNull(),
    accountType: text('account_type', {
      enum: ['asset', 'liability', 'equity', 'revenue', 'expense'],
    }).notNull(),
    accountSubType: text('account_sub_type'),
    parentAccountId: integer('parent_account_id'),
    description: text('description'),
    isActive: boolean('is_active').notNull().default(true),
    isSystemAccount: boolean('is_system_account').notNull().default(false),
    normalBalance: text('normal_balance', { enum: ['debit', 'credit'] }).notNull(),
    currentBalance: numeric('current_balance', { precision: 12, scale: 2 }).notNull().default('0'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('coa_tenant_code_unique').on(table.tenantId, table.accountCode),
    index('coa_type_idx').on(table.accountType),
    index('coa_parent_idx').on(table.parentAccountId),
    index('coa_active_idx').on(table.isActive),
  ]
)

export const journalEntries = pgTable(
  'journal_entries',
  {
    id: serial('id').primaryKey(),
    tenantId: integer('tenant_id')
      .notNull()
      .references(() => tenants.id),
    entryNumber: text('entry_number').notNull(),
    entryDate: timestamp('entry_date').notNull(),
    description: text('description').notNull(),
    referenceType: text('reference_type'),
    referenceId: integer('reference_id'),
    branchId: integer('branch_id').references(() => branches.id),
    status: text('status', {
      enum: ['draft', 'posted', 'reversed'],
    })
      .notNull()
      .default('draft'),
    isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
    createdBy: integer('created_by')
      .notNull()
      .references(() => users.id),
    postedBy: integer('posted_by').references(() => users.id),
    postedAt: timestamp('posted_at'),
    reversedBy: integer('reversed_by').references(() => users.id),
    reversedAt: timestamp('reversed_at'),
    reversalEntryId: integer('reversal_entry_id'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('je_tenant_number_unique').on(table.tenantId, table.entryNumber),
    index('je_date_idx').on(table.entryDate),
    index('je_status_idx').on(table.status),
    index('je_ref_idx').on(table.referenceType, table.referenceId),
  ]
)

export const journalEntryLines = pgTable(
  'journal_entry_lines',
  {
    id: serial('id').primaryKey(),
    journalEntryId: integer('journal_entry_id')
      .notNull()
      .references(() => journalEntries.id, { onDelete: 'cascade' }),
    accountId: integer('account_id')
      .notNull()
      .references(() => chartOfAccounts.id),
    debitAmount: numeric('debit_amount', { precision: 12, scale: 2 }).notNull().default('0'),
    creditAmount: numeric('credit_amount', { precision: 12, scale: 2 }).notNull().default('0'),
    description: text('description'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => [
    index('jel_entry_idx').on(table.journalEntryId),
    index('jel_account_idx').on(table.accountId),
  ]
)

export const accountBalances = pgTable(
  'account_balances',
  {
    id: serial('id').primaryKey(),
    tenantId: integer('tenant_id')
      .notNull()
      .references(() => tenants.id),
    accountId: integer('account_id')
      .notNull()
      .references(() => chartOfAccounts.id),
    branchId: integer('branch_id').references(() => branches.id),
    periodType: text('period_type', {
      enum: ['daily', 'monthly', 'yearly'],
    }).notNull(),
    periodDate: text('period_date').notNull(),
    openingBalance: numeric('opening_balance', { precision: 12, scale: 2 }).notNull().default('0'),
    debitTotal: numeric('debit_total', { precision: 12, scale: 2 }).notNull().default('0'),
    creditTotal: numeric('credit_total', { precision: 12, scale: 2 }).notNull().default('0'),
    closingBalance: numeric('closing_balance', { precision: 12, scale: 2 }).notNull().default('0'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => [
    index('ab_account_period_idx').on(table.accountId, table.periodType, table.periodDate),
    index('ab_branch_idx').on(table.branchId),
  ]
)
