import { pgTable, serial, text, boolean, timestamp, integer, numeric, jsonb } from 'drizzle-orm/pg-core'
import { tenants } from './tenants'
import { branches } from './branches'
import { users } from './users'

export const settings = pgTable('settings', {
  id: serial('id').primaryKey(),
  tenantId: integer('tenant_id')
    .notNull()
    .references(() => tenants.id),
  key: text('key').notNull(),
  value: jsonb('value'),
  category: text('category', {
    enum: ['general', 'company', 'tax', 'receipt', 'inventory', 'sales', 'notification', 'backup'],
  })
    .notNull()
    .default('general'),
  description: text('description'),
  updatedBy: integer('updated_by').references(() => users.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const businessSettings = pgTable('business_settings', {
  settingId: serial('setting_id').primaryKey(),
  tenantId: integer('tenant_id')
    .notNull()
    .references(() => tenants.id),
  branchId: integer('branch_id').references(() => branches.id),
  businessName: text('business_name').notNull(),
  businessRegistrationNo: text('business_registration_no'),
  businessType: text('business_type'),
  businessAddress: text('business_address'),
  businessCity: text('business_city'),
  businessState: text('business_state'),
  businessCountry: text('business_country'),
  businessPostalCode: text('business_postal_code'),
  businessPhone: text('business_phone'),
  businessEmail: text('business_email'),
  businessWebsite: text('business_website'),
  businessLogo: text('business_logo'),
  taxId: text('tax_id'),
  taxRate: numeric('tax_rate', { precision: 5, scale: 2 }).default('0'),
  taxName: text('tax_name').default('GST'),
  isTaxInclusive: boolean('is_tax_inclusive').default(false),
  secondaryTaxRate: numeric('secondary_tax_rate', { precision: 5, scale: 2 }).default('0'),
  secondaryTaxName: text('secondary_tax_name'),
  currencySymbol: text('currency_symbol').default('Rs.'),
  currencyCode: text('currency_code').default('PKR'),
  currencyPosition: text('currency_position').default('prefix'),
  decimalPlaces: integer('decimal_places').default(2),
  thousandSeparator: text('thousand_separator').default(','),
  decimalSeparator: text('decimal_separator').default('.'),
  receiptHeader: text('receipt_header'),
  receiptFooter: text('receipt_footer'),
  receiptLogo: text('receipt_logo'),
  invoicePrefix: text('invoice_prefix').default('INV'),
  invoiceNumberFormat: text('invoice_number_format').default('sequential'),
  invoiceStartingNumber: integer('invoice_starting_number').default(1),
  showTaxOnReceipt: boolean('show_tax_on_receipt').default(true),
  showQRCodeOnReceipt: boolean('show_qr_code_on_receipt').default(false),
  receiptFormat: text('receipt_format').default('pdf'),
  receiptPrimaryColor: text('receipt_primary_color').default('#1e40af'),
  receiptSecondaryColor: text('receipt_secondary_color').default('#64748b'),
  receiptFontSize: text('receipt_font_size').default('medium'),
  receiptCustomField1Label: text('receipt_custom_field_1_label'),
  receiptCustomField1Value: text('receipt_custom_field_1_value'),
  receiptCustomField2Label: text('receipt_custom_field_2_label'),
  receiptCustomField2Value: text('receipt_custom_field_2_value'),
  receiptCustomField3Label: text('receipt_custom_field_3_label'),
  receiptCustomField3Value: text('receipt_custom_field_3_value'),
  receiptTermsAndConditions: text('receipt_terms_and_conditions'),
  receiptShowBusinessLogo: boolean('receipt_show_business_logo').default(true),
  receiptAutoDownload: boolean('receipt_auto_download').default(true),
  lowStockThreshold: integer('low_stock_threshold').default(10),
  enableStockTracking: boolean('enable_stock_tracking').default(true),
  allowNegativeStock: boolean('allow_negative_stock').default(false),
  stockValuationMethod: text('stock_valuation_method').default('FIFO'),
  autoReorderEnabled: boolean('auto_reorder_enabled').default(false),
  autoReorderQuantity: integer('auto_reorder_quantity').default(50),
  defaultPaymentMethod: text('default_payment_method').default('Cash'),
  allowedPaymentMethods: text('allowed_payment_methods').default('Cash,Card,Bank Transfer,COD'),
  enableCashDrawer: boolean('enable_cash_drawer').default(true),
  openingCashBalance: numeric('opening_cash_balance', { precision: 12, scale: 2 }).default('0'),
  enableDiscounts: boolean('enable_discounts').default(true),
  maxDiscountPercentage: numeric('max_discount_percentage', { precision: 5, scale: 2 }).default('50'),
  requireCustomerForSale: boolean('require_customer_for_sale').default(false),
  enableCustomerLoyalty: boolean('enable_customer_loyalty').default(false),
  loyaltyPointsRatio: numeric('loyalty_points_ratio', { precision: 8, scale: 2 }).default('1'),
  expenseCategories: text('expense_categories').default(
    'Utilities,Rent,Salaries,Transportation,Maintenance,Marketing,Insurance,Other'
  ),
  expenseApprovalRequired: boolean('expense_approval_required').default(false),
  expenseApprovalLimit: numeric('expense_approval_limit', { precision: 12, scale: 2 }).default('10000'),
  enableReturns: boolean('enable_returns').default(true),
  returnWindowDays: integer('return_window_days').default(30),
  requireReceiptForReturn: boolean('require_receipt_for_return').default(true),
  refundMethod: text('refund_method').default('Original Payment Method'),
  enableEmailNotifications: boolean('enable_email_notifications').default(false),
  notificationEmail: text('notification_email'),
  lowStockNotifications: boolean('low_stock_notifications').default(true),
  dailySalesReport: boolean('daily_sales_report').default(false),
  workingDaysStart: text('working_days_start').default('Monday'),
  workingDaysEnd: text('working_days_end').default('Saturday'),
  openingTime: text('opening_time').default('09:00'),
  closingTime: text('closing_time').default('18:00'),
  dateFormat: text('date_format').default('DD/MM/YYYY'),
  timeFormat: text('time_format').default('24-hour'),
  language: text('language').default('en'),
  timezone: text('timezone').default('UTC'),
  sessionTimeoutMinutes: integer('session_timeout_minutes').default(60),
  requirePasswordChange: boolean('require_password_change').default(false),
  passwordChangeIntervalDays: integer('password_change_interval_days').default(90),
  enableAuditLogs: boolean('enable_audit_logs').default(true),
  isActive: boolean('is_active').default(true),
  isDefault: boolean('is_default').default(false),
  notes: text('notes'),
  createdBy: integer('created_by').references(() => users.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})
